file-upload:
  subs-api:
    host: https://example.com
    submissionStatusURI: "%s/api/submissions/%s/submissionStatus"
    submissionURI: "%s/api/submissions/%s"
  security:
    issuer: https://some.secure.com
    certificatePath: aap_public_key.der
  sourceBasePath: src/test/resources
  targetBasePath: ready_to_agent
  filePrefixForLocalProcessing: local_file_prefix
  globus:
    proxy:
      host: pg-wwwcache.ebi.ac.uk
      port: 3128
    url:
      auth: https://auth.globus.org
      transfer: https://transfer.api.globusonline.org
    client:
      id: fake-id
      secret: fake-secret
    transferRefreshToken: fake-refresh-token
    hostEndpoint:
      id: fake-id
      baseDirectory: /~/fake/dir
      activation:
        username: fake-username
        password: fake-password
    baseUploadDirectory: /fake/dir


fileProcessing-listener:
  checksum-calculator:
    jobName: fileProcessing-listener.checksum-calculator.jobName
  content-validator:
    jobName: fileProcessing-listener.content-validator.jobName

usi:
  repositoryMapping:
    analysis: variantCalls
    assayData:
      - sequencingRuns
      - metabolightsAssayData
    assay:
      - sequencingExperiments
      - metabolomicsAssays
    egaDacPolicy: egaDacPolicies
    egaDac: egaDacs
    egaDataset: egaDatasets
    project: projects
    protocol: metabolightsProtocols
    sampleGroup:
    sample: samples
    study:
      - enaStudies
      - metabolomicsStudies
  archive:
    dispatcher:
      enabled:
        - BioSamples
        - BioStudies
        - Ena
      data-types:
        BioSamples: samples
        BioStudies: projects
        Ena:
          - enaStudies
          - sequencingExperiments
          - sequencingRuns
