subs-api:
  host: https://example.com
  submissionStatusURI: "%s/api/submissions/%s/submissionStatus"
  submissionURI: "%s/api/submissions/%s"


security:
  issuer: https://some.secure.com
  certificatePath: test_public_key.der
